### PR TITLE
Provide a toString() implementation that outputs response body as a human readable string rather than a byte array.

### PR DESCRIPTION
**Pull request by kaiwaldron**

### CODE REVIEW

**Comment by jkwatson** [comment]
My 2 cents:  I think we should consider truncating the body to some limited # of characters, rather than dumping the entire body out in the toString.  Otherwise, :+1:

**Comment by kaiwaldron** [comment]
I'm open to that -- what seems like a reasonable limit to you?

**Comment by jkwatson** [comment]
A couple hundred?  No idea what's a good number.  I've just seen similar logging flood the logs with many K of html error pages, which isn't so useful.  :)

**Comment by joelhoffman** [comment]
Agreed, and I would even strip out \n and \r, and add the full length and maybe a hash to see whether subsequent items are changing.

**Comment by breedx2** [comment]
Hey @kaiwaldron -- if you limit the body output we can get this merged.
Thanks!

**Pull request closed without merging**
