### PR TITLE
Http template enhancements

### PR DESCRIPTION
**Pull request by jkwatson**
Mostly, this adds code to use the retryer for GETs, PUTs and DELETEs, and not just POSTs, as it was doing before.

### CODE REVIEW

**Comment by zradick** [comment]
Looks good to me.  Reuse of the retry strategy for all supported HTTP verbs seems like an obvious choice.  :+1:

**Comment by jkwatson** [comment]
Is anybody out there?  I'd love a merge on this; I'd hate to have to self-merge it!

**Comment by breedx2** [comment]
Looks good to me too.  I like the expanded use of retryer...and the exception handling cleanup is an added bonus.  Merging!

**Comment by jkwatson** [comment]
I published this to the oss.sonatype snapshot repo this morning. We can figure out making a non-snapshot build at some point.  One interesting fact... if you publish a non-snapshot build with the same build number as an existing snapshot, sonatype deletes the snapshots from the repository, so client builds that depend on the snapshot version will break.  I found this out the hard way.  :)

**Pull request merged**
