### PR TITLE
Ensure that if gson is provided to httptemplate, the content type is application/json

### PR DESCRIPTION
**Pull request by joelhoffman**

### CODE REVIEW

**Comment by jkwatson** [comment]
What use-case is this trying to protect the user from?

**Comment by joelhoffman** [comment]
It's specifically trying to protect the weather collection module from other developers' refactorings of shared code.  If you construct the httptemplate with a gson object, but provide a content type of "*/*" (not a real content type, but handy for browsers) then gson will not be invoked from a call to  HttpTemplate.post(String fullUri, Object bodyToPost).  It's incoherent to provide a value for gson that is not intented to be used.  This scenario occurred, so I'm preventing it.

There appears to be some more sloppy use of "contentType" here where a passed-in parameter is mixed up with a field, maybe I should clean that up as well.

**Comment by jkwatson** [comment]
I had missed that is was just on the `POST` side of things that the assertion was being made.  Seems fine to me.

**Comment by joelhoffman** [comment]
That's cleaned up. Probably should be a different PR, but there it is.

**Pull request merged**
